# Generated by Django 3.1 on 2022-05-26 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piplinedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibrationCount', models.FloatField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
