# Generated by Django 3.1 on 2022-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piplinedata',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piplinedata',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
